name: xpeapp_admin
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.4.0+22

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.1.1
  firebase_core: ^4.3.0
  flutter_riverpod: ^3.0.3
  yaki_ui:
    git:
      url: https://github.com/XPEHO/yaki_ui.git
      path: flutter
      ref: 0.4.4
  firebase_auth: ^6.1.3
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  flutter_localization: ^0.3.3
  firebase_storage: ^13.0.5
  flutter_localizations:
    sdk: flutter
  http: ^1.6.0
  fake_cloud_firestore: ^4.0.0
  dio: ^5.9.0
  retrofit: ^4.9.1
  file_picker: ^10.3.7
  google_sign_in: ^7.2.0
  csv: ^6.0.0
  url_launcher_web: ^2.4.1
  json_annotation: ^4.9.0
  http_parser: ^4.1.2
  syncfusion_flutter_charts: ^32.1.19
  universal_html: ^2.3.0
  go_router: ^17.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  retrofit_generator: ^10.2.1
  build_runner: ^2.10.4
  json_serializable: ^6.11.2
  mockito: ^5.6.1
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/logo_xpeapp.png"
    background_color: "#A0CE4E"
    theme_color: "#A0CE4E"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: SF Pro Rounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
